name: code quality
on:
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: code-quality qodana
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: pull_request
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master
          ref: master
      - name: copy config file
        run: cp pull_request/qodana.yml master/qodana.yml
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: "Create folder"
        run: "mkdir -p ${{ github.workspace }}/result/master"
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v3.2.1
        with:
          project-dir: "${{ github.workspace }}/master"
          results-dir: "${{ github.workspace }}/result/master"
      - name: Qodana - Code Inspection
        id: qodana
        uses: JetBrains/qodana-action@v3.2.1
        with:
          project-dir: "${{ github.workspace }}/pull_request"
          baseline-path: "/data/results/master/qodana.sarif.json"
          baseline-include-absent: true
          results-dir: "${{ github.workspace }}/result"
          fail-threshold: 1
      - name: SARIF Annotator
        uses: SirYwell/sarif-annotator@b0c46b2ddbb44b1f58eae3eea9453786381d79b3
        with:
          source: qodana
          report-path: ${{ steps.qodana.outputs.results-json-path }}
          baseline-state-filter: 'new'
