name: 'Sarif Annotator Test'
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SirYwell/sarif-annotator@9081f18a657d551349aad7361b5782f7cc700830
        with:
          report-path: 'report/qodana.sarif.json'
          source: 'qodana'

