name: code quality
on:
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: code-quality qodana
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Qodana - Code Inspection
        id: qodana
        uses: JetBrains/qodana-action@v3.2.1
      - name: SARIF Annotator
        uses: SirYwell/sarif-annotator@29512b74b4db8fefc8981dce940363dca6f45859
        with:
          source: qodana
          report-path: ${{ steps.qodana.outputs.results-json-path }}
          baseline-state-filter: 'new'
