name: 'Sarif Annotator Test'
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SirYwell/sarif-annotator@93aed1597275aa9961b6e700a2397782bb9e20b4
        with:
          report-path: 'report/qodana.sarif.json'
          source: 'qodana'

