name: 'Sarif Annotator Test'
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SirYwell/sarif-annotator@a4b07dca643e2e1cfb9d0aa6518f708c109b6c43
        with:
          report-path: 'report/qodana.sarif.json'
          source: 'qodana'

